### ISSUE TITLE
The thanks are in the wrong order

### ISSUE THREAD

**Issue by sunnyeyez123** [sunnyeyez123/thanks#6]
the newest thanks should be on the top of the list.

**Comment by isaprykin** [comment]
Resolved in https://github.com/sunnyeyez123/thanks/commit/d4d24dabca9b422f9701d5cb95fff95b6d26ad79.  Thanks for reporting!

**Comment by sunnyeyez123** [comment]
The dates are still in the wrong order. I think you're sorting them as strings rather than dates!

**Comment by sunnyeyez123** [comment]
Igor, using your laptop:

oh jeez thanks for reporting.
Fixed in https://github.com/sunnyeyez123/thanks/commit/45a80fd97d174cdf22b9822f9a0d530f41255fa3 and https://github.com/sunnyeyez123/thanks/commit/af921fcc71ea26cde438881b2b463df6afa9eadb.
